### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/ScientificTypes.jl#111]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

(**breaking release**) ScientificTypes 2.0 is essentially a copy of MLJScientificTypes 0.4.8. The code
at ScientificTypes 1.1.2 was moved to ScientificTypesBase 1.0. See #125 for details.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

(**breaking release**) ScientificTypes 2.0 is essentially a copy of MLJScientificTypes 0.4.8. The code
at ScientificTypes 1.1.2 was moved to ScientificTypesBase 1.0. See #125 for details.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

(**breaking release**) ScientificTypes 2.0 is essentially a copy of MLJScientificTypes 0.4.8. The code
at ScientificTypes 1.1.2 was moved to ScientificTypesBase 1.0. See #125 for details.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- [x] (**enhancement**) Implement `sctiype` for `Denisty` and `Sampleable` (#143)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**bug fix**) Fix `schema(X)` for a wrapped categorical matrix `X` (#146) @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

cc @pazzo83

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

cc @kd-iqvia

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

cc @pazzo83

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Allow column names to be entered as strings (in addition to symbols) when using `coerce` on tables (#161) @juliohm

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [ ] Remove experimental `scitype()` implementation for text analysis (being moved to new pkg MLJText.lj)
- [ ] Remove `scitype()` implementation for persistence diagrams

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

From the PR, #174 (@OkonSamuel):

- (**breaking**) Remove the `nrows` field from objects returned by `schema`, and modify how these are displayed
- Update `Schema` constructor to reflect updates to `Tables.Schema`
- (**enhancement**) Implement the Tables.jl interface for objects returned by `schema`
- (**enhancement**) improve performance of schema and scitype methods for small to medium size tables
- Avoid schema errors for extremely wide tables.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master


Release notes:

Dumps support for Julia 1.0 in favor of Julia 1.10 (current LTS release) and higher

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Extend the compatibility requirement for CategoricalArrays (#199)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

(**new feature**) Arrange for `scitype()` to print out the active type hierarchy (#210)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**improvement**) Fix the display of objects returned by `schema(X)` by suppressing row truncation (#214)
